make SILENT=yes
This allows to run make more silently.

Also, turns off debug info for binaries by default,
but adds a switch to get it back easily

    ./configure --debug

diff --git a/tests/Makefile b/tests/Makefile
--- a/tests/Makefile
+++ b/tests/Makefile
@@ -23,8 +23,7 @@ TESTS = \
  tests2-dir \
  pp-dir
 
-BTESTS = btest test2b
-
+BTESTS = btest test1b
 # test4_static -- Not all relocation types are implemented yet.
 # asmtest / asmtest2 -- minor differences with gcc
 
@@ -34,9 +33,6 @@ ifeq ($(ARCH),i386)
  TESTS += $(BTESTS)
 endif
 ifeq ($(ARCH),x86_64)
- TESTS += $(BTESTS)
-endif
-ifdef CONFIG_WIN32
  TESTS += $(BTESTS)
 endif
 endif
@@ -52,12 +48,9 @@ endif
 ifeq (,$(filter i386 x86_64,$(ARCH)))
  TESTS := $(filter-out dlltest asm-c-connect-test,$(TESTS))
 endif
-ifndef CONFIG_cross
- TESTS := $(filter-out cross-%,$(TESTS))
-endif
 
 ifeq ($(OS),Windows_NT) # for libtcc_test to find libtcc.dll
- PATH := $(CURDIR)/$(TOP)$(if $(findstring :\,$(PATH)),;,:)$(PATH)
+ PATH := $(CURDIR)/$(TOP)$(if $(findstring ;,$(PATH)),;,:)$(PATH)
 endif
 
 ifeq ($(ARCH),arm)
@@ -75,11 +68,10 @@ endif
 RUN_TCC = $(NATIVE_DEFINES) -run $(TOPSRC)/tcc.c $(TCCFLAGS)
 DISAS = objdump -d
 DUMPTCC = (set -x; $(TOP)/tcc -vv; ldd $(TOP)/tcc; exit 1)
-Q = # >/dev/null 2>&1
 
 all test :
-	$(MAKE) clean-s
-	$(MAKE) $(TESTS)
+	@$(MAKE) --no-print-directory -s clean
+	@$(MAKE) --no-print-directory -s -r $(TESTS)
 
 hello-exe: ../examples/ex1.c
 	@echo ------------ $@ ------------
@@ -93,7 +85,10 @@ libtes%: libtcc_tes%$(EXESUF)
 	@echo ------------ $@ ------------
 	./libtcc_tes$*$(EXESUF) $(TOPSRC)/tcc.c $(TCCFLAGS) $(NATIVE_DEFINES)
 
-libtcc_tes%$(EXESUF): libtcc_tes%.c $(LIBTCC)
+libtcc_test$(EXESUF): libtcc_test.c $(LIBTCC)
+	$(CC) -o $@ $^ $(CFLAGS) $(LIBS)
+
+libtcc_test_mt$(EXESUF): libtcc_test_mt.c $(LIBTCC)
 	$(CC) -o $@ $^ $(CFLAGS) $(LIBS)
 
 %-dir:
@@ -108,19 +103,19 @@ test.ref: tcctest.c
 # auto test
 test1 test1b: tcctest.c test.ref
 	@echo ------------ $@ ------------
-	$(TCC) -w -run $< > test.out1 $Q
+	$(TCC) $(RUN_TCC) -w -run $< > test.out1
 	@diff -u test.ref test.out1 && echo "$(AUTO_TEST) OK"
 
 # iterated test2 (compile tcc then compile tcctest.c !)
 test2 test2b: tcctest.c test.ref
 	@echo ------------ $@ ------------
-	$(TCC) $(RUN_TCC) $(RUN_TCC) -w -run $< > test.out2 $Q
+	$(TCC) $(RUN_TCC) $(RUN_TCC) -w -run $< > test.out2
 	@diff -u test.ref test.out2 && echo "$(AUTO_TEST)2 OK"
 
 # iterated test3 (compile tcc then compile tcc then compile tcctest.c !)
 test3 test3b: tcctest.c test.ref
 	@echo ------------ $@ ------------
-	$(TCC) $(RUN_TCC) $(RUN_TCC) $(RUN_TCC) -w -run $< > test.out3 $Q
+	$(TCC) $(RUN_TCC) $(RUN_TCC) $(RUN_TCC) -w -run $< > test.out3
 	@diff -u test.ref test.out3 && echo "$(AUTO_TEST)3 OK"
 
 AUTO_TEST = Auto Test
@@ -145,6 +140,7 @@ test4: tcctest.c test.ref
 	@if diff -u test.ref test4.out ; then echo "BCheck $(AUTO_TEST) OK"; fi
 
 test4_static: tcctest.c test.ref
+	@echo ------------ $@ ------------
 # static output.
 	$(TCC) -static -o tcctest2 $<
 	./tcctest2 > test2.out
@@ -170,6 +166,7 @@ memtest:
 	$(CC) $(CFLAGS) $(NATIVE_DEFINES) -DMEM_DEBUG=2 $(TOPSRC)/tcc.c $(LIBS) -o memtest-tcc$(EXESUF)
 	./memtest-tcc$(EXESUF) $(TCCFLAGS) $(NATIVE_DEFINES) $(TOPSRC)/tcc.c $(LIBS)
 	./memtest-tcc$(EXESUF) $(TCCFLAGS) $(NATIVE_DEFINES) -run $(TOPSRC)/tcc.c $(TCCFLAGS) -w $(TOPSRC)/tests/tcctest.c
+	@echo OK
 
 # memory and bound check auto test
 BOUNDS_OK  = 1 4 8 10 14 16
@@ -178,17 +175,17 @@ BOUNDS_FAIL= 2 5 6 7 9 11 12 13 15 17
 btest: boundtest.c
 	@echo ------------ $@ ------------
 	@for i in $(BOUNDS_OK); do \
-	   if $(TCC) -b -run $< $$i ; then \
-	       echo "- Test $$i succeeded as expected" ; \
+	   if $(TCC) -b -run $< $$i >/dev/null 2>&1 ; then \
+	       echo "Test $$i succeeded as expected" ; \
 	   else\
-	       echo "- Failed positive test $$i" ; exit 1 ; \
+	       echo "Failed positive test $$i" ; exit 1 ; \
 	   fi ;\
 	done ;\
 	for i in $(BOUNDS_FAIL); do \
-	   if $(TCC) -b -bt1 -run $< $$i ; then \
-	       echo "- Failed negative test $$i" ; exit 1 ;\
+	   if $(TCC) -b -bt1 -run $< $$i >/dev/null 2>&1 ; then \
+	       echo "Failed negative test $$i" ; exit 1 ;\
 	   else\
-	       echo "- Test $$i failed as expected" ; \
+	       echo "Test $$i failed as expected" ; \
 	   fi ;\
 	done ;\
 	echo Bound test OK
@@ -202,6 +199,7 @@ speedtest: ex2 ex3
 	time $(TCC) -run $(TOPSRC)/examples/ex3.c 35
 
 weaktest: tcctest.c test.ref
+	@echo ------------ $@ ------------
 	$(TCC) -c $< -o weaktest.tcc.o
 	$(CC) -c $< -o weaktest.gcc.o $(NATIVE_DEFINES) $(CFLAGS) -w -O0 -std=gnu99 -fno-omit-frame-pointer
 	objdump -t weaktest.tcc.o | grep ' w ' | sed -e 's/.* \([a-zA-Z0-9_]*\)$$/\1/' | LC_ALL=C sort > weaktest.tcc.o.txt
@@ -227,22 +225,19 @@ asmtest2: MAYBE_RUN_TCC = $(RUN_TCC)
 
 # Check that code generated by libtcc is binary compatible with
 # that generated by CC
-abitest-cc$(EXESUF): abitest.c $(LIBTCC)
+abitest-cc.exe: abitest.c $(LIBTCC)
 	$(CC) -o $@ $^ $(CFLAGS) $(LIBS) -w
 
-abitest-tcc$(EXESUF): abitest.c libtcc.c
-	$(TCC) -o $@ $^ $(NATIVE_DEFINES) $(LIBS)
+abitest-tcc.exe: abitest.c libtcc.c
+	$(TCC) -o $@ $^ $(LIBS)
 
-ABITESTS := abitest-cc$(EXESUF)
-ifneq ($(CONFIG_arm_eabi),yes) # not ARM soft-float
- ABITESTS += abitest-tcc$(EXESUF)
-endif
-
-abitest: $(ABITESTS)
+abitest-% : abitest-%.exe
 	@echo ------------ $@ ------------
-	./abitest-cc$(EXESUF) $(TCCFLAGS)
+	./$< $(TCCFLAGS)
+
+abitest: abitest-cc
 ifneq ($(CONFIG_arm_eabi),yes) # not ARM soft-float
-	./abitest-tcc$(EXESUF) $(TCCFLAGS)
+abitest: abitest-tcc
 endif
 
 vla_test$(EXESUF): vla_test.c
@@ -265,22 +260,18 @@ asm-c-connect-test: asm-c-connect$(EXESUF) asm-c-connect-sep$(EXESUF)
 	@echo ------------ $@ ------------
 	./asm-c-connect$(EXESUF) > asm-c-connect.out1 && cat asm-c-connect.out1
 	./asm-c-connect-sep$(EXESUF) > asm-c-connect.out2 && cat asm-c-connect.out2
-	@diff -u asm-c-connect.out1 asm-c-connect.out2 && echo "ok"
+	@diff -u asm-c-connect.out1 asm-c-connect.out2 || (echo "error"; exit 1)
+
+TCC_YY = $(foreach T,$(TCC_X),$(if $(wildcard $(TOP)/$T-tcc$(EXESUF)),$T))
 
 cross-test :
+	$(if $(strip $(TCC_YY)),\
+	    $(MAKE) $(foreach T,$(TCC_YY),cross-$T.test) --no-print-directory,:)
+
+cross-%.test :
 	@echo ------------ $@ ------------
-	$(TOP)/i386-tcc$(EXESUF) $(TCCFLAGS-unx) -c $(TOPSRC)/examples/ex3.c && echo "ok"
-	$(TOP)/i386-win32-tcc$(EXESUF) $(TCCFLAGS-win) $(TOPSRC)/examples/ex3.c && echo "ok"
-	$(TOP)/x86_64-tcc$(EXESUF) $(TCCFLAGS-unx) -c $(TOPSRC)/examples/ex3.c && echo "ok"
-	$(TOP)/x86_64-win32-tcc$(EXESUF) $(TCCFLAGS-win) $(TOPSRC)/examples/ex3.c && echo "ok"
-	$(TOP)/arm-tcc$(EXESUF) $(TCCFLAGS-unx) -c $(TOPSRC)/examples/ex3.c && echo "ok"
-	$(TOP)/arm-wince-tcc$(EXESUF) $(TCCFLAGS-win) -c $(TOPSRC)/examples/ex3.c && echo "ok"
-	$(TOP)/arm64-tcc$(EXESUF) $(TCCFLAGS-unx) -c $(TOPSRC)/examples/ex3.c && echo "ok"
-	$(TOP)/riscv64-tcc$(EXESUF) $(TCCFLAGS-unx) -c $(TOPSRC)/examples/ex3.c && echo "ok"
-	$(TOP)/c67-tcc$(EXESUF) $(TCCFLAGS-unx) -c $(TOPSRC)/examples/ex3.c && echo "ok"
-	$(TOP)/i386-win32-tcc$(EXESUF) $(TCCFLAGS-win) $(TOPSRC)/win32/examples/hello_win.c && echo "ok"
-	$(TOP)/x86_64-win32-tcc$(EXESUF) $(TCCFLAGS-win) $(TOPSRC)/win32/examples/hello_win.c && echo "ok"
-	$(TOP)/arm-wince-tcc$(EXESUF) $(TCCFLAGS-win) -c $(TOPSRC)/win32/examples/hello_win.c && echo "ok"
+	$(TOP)/$*-tcc$(EXESUF) -v $(TCCFLAGS-$(if $(findstring win,$*),win,unx))\
+	    -c $(TOPSRC)/examples/ex3.c
 
 # targets for development
 %.bin: %.c tcc
@@ -306,6 +297,3 @@ clean:
 	@$(MAKE) -C tests2 $@
 	@$(MAKE) -C pp $@
 
-# silent clean, used before running tests
-clean-s:
-	@$(MAKE) -s --no-print-directory clean
